### ISSUE TITLE
OSX/Linux platform differences on subshell invocation

### ISSUE THREAD

**Issue by jonasschneider** [stripe/subprocess#11]
As described [in this gist](https://gist.github.com/jonasschneider/0a5d8d8a119266919431), Ruby's ridiculous `exec` implementation that spawns a subshell if `args.length==1`, combined with Subprocess's behaviour of [adding quotes here](https://github.com/stripe/subprocess/blob/242aeadc1c59671b4470f9d4271f8c7d406db872/lib/subprocess.rb#L340-L342) causes behaviour differences between OS X and Linux.

Are you willing to work around this? Though I can certainly see how this causes problems in the strange case where the path to your executable contains shell-relevant characters. Maybe we can just shellescape `cmd[0]` and leave out the quotes?

**Comment by zenazn** [comment]
So I guess 91cf294ce7ef2fb3e8349f4205cd87ddfdb46f39 is probably enough to fix this. I'm not super thrilled by the solution though...

**Comment by jonasschneider** [comment]
Well, the solution is of course as always piling hacks on top of hacks. I guess you *could* also write a cext that calls execve... :rocket: 

I'd have suggested using $SHELL instead of hardcoding sh, but it looks like this is what Ruby does as well.

**Comment by zenazn** [comment]
I don't want to touch shell compatibility with a ten foot pole :)

I'll poke some more people for their Opinions on this, but I think there's an okay chance this gets merged

**Comment by zenazn** [comment]
@jonasschneider alright would you mind trying this again? I think everything is ponies now :)

**Comment by jonasschneider** [comment]
Yup, that does it! :confetti_ball:
