### ISSUE TITLE
Update version in rubygems

### ISSUE THREAD

**Issue by AlexJF** [stripe/subprocess#43]
Latest version in rubygems is 1.3.2 but several important bugfixes were done since that release. 

In particular, I'm suffering from missing stdout content fixed by https://github.com/stripe/subprocess/commit/28e0c7f1717a195bed27c91a2564f172883310b3. Running version 1.5.2 from a source install seems to fix the issue. 

Can we bump this module's version in rubygems?

**Comment by fotinakis** [comment]
Would like this! Just hit a problem because subprocess rubygems version is out of date.
