### ISSUE TITLE
 Compatibility Inquiry: subprocess 1.5.6 with Ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [stripe/subprocess#73]
Hi,

I'm seeking confirmation regarding the compatibility of the subprocess 1.5.6  with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on https://github.com/stripe/subprocess/blob/master/.github/workflows/ruby.yml
matrix:
 os: [ubuntu-latest, macos-latest]
 ruby: [2.5, 2.6, 2.7].
Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by qaisjp** [comment]
Hi! I think we are on Ruby 3.1 internally but I'll double check for you tomorrow.

**Comment by sydverisk** [comment]
Hi @qaisjp, thanks for the update, I look forward for your response!

**Comment by qaisjp** [comment]
We are indeed on Ruby 3.1 internally, and plan to upgrade soon.

In https://github.com/stripe/subprocess/pull/74 it looks like tests pass for Ruby 3.3 though, so I'd give it a try! Please report back if you run into any issues :)

Hope that helps.
